development:
  # Chain configuration
  xgt:
    # Chain configuration
    # addressPrefix: TST
    # host: http://localhost:8751
    # chainId: 18dcf0a285365fc58b71f18b3d3fec954aa0c141c44e4e5cb4cf777b9eab274e
    # privKey: 5JNHfZYKGaomSFvd4NUdQ9qMcEAC43kujbfjueTHpVapX1Kzq2n

    address_prefix : TST
    host : http://3.214.219.151:8751
    chain_id : 18dcf0a285365fc58b71f18b3d3fec954aa0c141c44e4e5cb4cf777b9eab274e
    private_key : 5JNHfZYKGaomSFvd4NUdQ9qMcEAC43kujbfjueTHpVapX1Kzq2n

